Update index.html
htmlacademy-htmlcss/1859921-device-32 pull request #2
Opened 2021-09-25 12:10 UTC by EkaterinaDmitr

2021-09-26 19:39 UTC, sealeye commented on catalog.html
> +              <span class="visually-hidden"> Поиск </span>
Тут будет форма с инпутом и кнопкой внутри.

2021-09-26 19:40 UTC, sealeye commented on catalog.html
> +                <button class="range-toggle toggle-min" type="button">
Кроме кнопок понадобится ещё два дива, которые будут отвечать за шкалы.

2021-09-26 19:40 UTC, sealeye commented on catalog.html
> +                                <span class="control-label">Черный</span>
Текст можно не оборачивать в спан, это лишняя обертка.

2021-09-26 19:42 UTC, sealeye commented on catalog.html
> +          <form class="sorting-type">
Сортировка это не форма, так как для этого не нужно получать данные с сервера, вся сортировка обычно осуществляется на js.

2021-09-26 19:43 UTC, sealeye commented on catalog.html
> +            </a>
Тут закрыта ссылка, которая не открыта.

2021-09-26 19:43 UTC, sealeye commented on catalog.html
> +              <button class="button" type="submit">Показать</button>
Кнопкам нужно указать тип submit только внутри форм, тут нет формы. Тут может быть только тип button

2021-09-26 19:44 UTC, sealeye commented on catalog.html
> +              <a class="product-card-link" href="#">
Странно оборачивать в ссылку картинку и подпись, но при этом не оборачивать цену, по сетке не получится выставить так элементы.

2021-09-26 19:45 UTC, sealeye commented on catalog.html
> +        <p>Санкт-Петербург, набережная
Это параграф нужно поместить в секцию с лого.

2021-09-26 19:45 UTC, sealeye commented on catalog.html
> +          <img class="footer-contacts-logo" src="" alt="Логотип">
Не на главной странице лого это всегда ссылка.

2021-09-26 19:45 UTC, sealeye commented on catalog.html
> +            <li>Доставка</li>
Внутри должны быть ссылки

2021-09-26 19:46 UTC, sealeye commented on catalog.html
> +          <h2 class="page-footer-title">Тел</h2>
Телефон это тоже должна быть ссылка

2021-09-26 19:46 UTC, sealeye commented on catalog.html
> +        <ul class="footer-social-list">
Этот список должен быть внутри секции, которая выше.

2021-09-26 19:47 UTC, sealeye commented on index.html
> +          <a class="navigation-logo" href="index.html">
Ссылка не может вести на страницу на которой мы и так находимся. Поэтому в таких случаях можно удалить href.

2021-09-26 19:49 UTC, sealeye commented on index.html
> +          <dl>
Здесь не список определений. Между dt и dd должно быть можно поставить слово "это" чтобы получилось определение, здесь явно не получится. Вместо этого должны быть заголовок и параграф.

2021-09-26 19:50 UTC, sealeye commented on index.html
> +          <ol class="slider-pagination">
Это не нумерованный список, а обычный, потому что нет порядковых номеров.

2021-09-26 19:50 UTC, sealeye commented on index.html
> +        <section>
Содержимое слайда должно быть внутри секции slider

2021-09-26 19:50 UTC, sealeye commented on index.html
> +        <section>
В разметке должно быть три слайда

2021-09-26 19:52 UTC, sealeye commented on index.html
> +          <table>
Это не таблица, потому что в таблице каждая колонка должна иметь какое-то название, здесь же такого нет. Здесь как раз подойдет dl потому что это определения.

2021-09-26 19:52 UTC, sealeye commented on index.html
> +          <ul class="categories-table">
Тут должен быть один список. Внутри каждого элемента списка будет ссылка. Внутри ссылки картинка и текст.

2021-09-26 19:53 UTC, sealeye commented on index.html
> +            <li>Доставка</li>
Это интерактивные кликабельные элементы, поэтому и теги должны быть интерактивные.

2021-09-26 19:53 UTC, sealeye commented on index.html
> +          <table>
Это не таблица, здесь нет табличных данных.

2021-09-26 19:54 UTC, sealeye commented on index.html
> +          <table>
В разметке должно быть три слайда.

2021-09-26 19:54 UTC, sealeye commented on index.html
> +              <td> Доставка</td>
Это заголовок

2021-09-26 19:54 UTC, sealeye commented on index.html
> +              <td>Мы с удовольствием доставим ваш товар прямо
А это параграф

2021-09-26 19:54 UTC, sealeye commented on index.html
> +          <img scr="illustration-delivery1.png">
Картинка это часть слайда

2021-09-26 19:54 UTC, sealeye commented on index.html
> +        <section class="about.firm">
В классах не должно быть точек.

2021-09-26 19:55 UTC, sealeye commented on index.html
> +            <button class="about"> <a href=#></a>Подробнее о нас</button>
Нельзя оборачивать ссылку в кнопку, здесь должна быть просто ссылка.

2021-09-26 19:55 UTC, sealeye commented on index.html
> +          <button class="write to us"> <a href=#></a>Напишите нам</button>
Тут тоже просто ссылка.

2021-09-26 19:56 UTC, sealeye reviewed
В целом, ты выбираешь правильные теги, но с группировкой сейчас есть проблемы и нужно проверить код валидатором.

2021-09-27 20:07 UTC, sealeye commented on catalog.html
> +              <input type="submit" value="Поиск по сайту">
Инпут не может работать без тега form, его обязательно нужно в него обернуть.

2021-09-27 20:09 UTC, sealeye commented on catalog.html
> +              <img class="product-card-image" src="" alt="">
Ссылка должна быть в каждом товаре

2021-09-27 20:10 UTC, sealeye commented on catalog.html
> +          <h2 class="page-footer-title">Тел</h2>
Нужно добавить сам номер телефона

2021-09-27 20:11 UTC, sealeye commented on index.html
> +            <h2>Порхает как бабочка, жалит как пчела!
Этот текст и весь контент слайда нужно сгруппировать в один тег, чтобы была возможность добавить три слайда с разной информацией.

2021-09-27 20:11 UTC, sealeye commented on index.html
> +              <h2> Доставка</h2>
Нужно из контента сформировать слайд, чтобы была возможность добавить три слайда.

2021-09-27 20:12 UTC, sealeye commented on index.html
> +            <h2 class="page-footer-title">соц сети</h2>
Нужно скорректировать разметку футера как в каталоге

2021-09-27 20:25 UTC, EkaterinaDmitr commented on index.html
> +            <h2>Порхает как бабочка, жалит как пчела!
недостаточно <section class="slider"> ?

2021-09-27 20:25 UTC, EkaterinaDmitr commented on index.html
> +            <h2>Порхает как бабочка, жалит как пчела!
section class="slider"

2021-09-27 20:40 UTC, EkaterinaDmitr commented on index.html
> +              <h2> Доставка</h2>
обернуть в див ?

2021-09-28 21:29 UTC, sealeye requested changes
До сих пор есть непонимание как строится контент слайдера. Вот пример зюразметки типичного слайдера https://codepen.io/suez/pen/ByvKXE

2021-09-28 21:29 UTC, sealeye commented on catalog.html
> +                <input type="submit" value="Поиск по сайту">
Тут должен быть тип search для поиска

2021-09-28 21:29 UTC, sealeye commented on catalog.html
> +                <a class="product-card-link" href="#">
В остальных карточках ссылка включает в себя все элементы, нужно соблюдать единообразие.

2021-09-28 21:29 UTC, sealeye commented on index.html
> +            <h2>Порхает как бабочка, жалит как пчела!
Кроме slider в целом должны быть отдельные slide. 
Slider включает в себя три slide и кнопки управления слайдером.

2021-09-28 21:29 UTC, sealeye commented on index.html
> +      <div class="slider1">
В названии классов не нужно использовать числительные, так как они привязаны к порядку, а порядок всегда может измениться.

2021-09-28 21:29 UTC, sealeye commented on index.html
> +      <div class="slider1">
Сейчас ты добавила вот эту по сути лишнюю обёртку, а нужно внутри сгруппировать заголовок, текст и список перечислений в один общий div. Посмотри в макете есть пример всех слайдов, там меняется информация и соответственно это три разных блока, которые изначально есть в разметке, но только один из них видим, остальные скрыты. Соответственно тебе в разметку нужно будет добавить три эти разных сущности и для этого они должны быть сгруппированы.

2021-09-28 21:29 UTC, sealeye commented on index.html
> +              <h2> Доставка</h2>
Вот здесь тоже не сформированы слайды, их должно быть три.

2021-09-29 22:11 UTC, merged